export default defineNuxtConfig({
  compatibilityDate: '2026-04-20',
  devtools: { enabled: true },
  css: ['@unocss/reset/tailwind.css', '~/assets/main.css'],
  modules: [
    '@unocss/nuxt',
    'reka-ui/nuxt',
    '@nuxtjs/i18n',
  ],
  i18n: {
    vueI18n: 'i18n.config.ts',
    defaultLocale: 'fr',
    strategy: 'no_prefix',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'glitchmao-locale',
      redirectOn: 'root',
    },
    locales: [
      { code: 'fr', name: 'Francais' },
      { code: 'en', name: 'English' },
    ],
  },
  typescript: {
    strict: true,
    typeCheck: false,
  },
  runtimeConfig: {
    databaseUrl: process.env.DATABASE_URL ?? '',
    gpgKeyId: process.env.GPG_KEY_ID ?? '',
    gpgDefaultKeyName: process.env.GPG_DEFAULT_KEY_NAME ?? 'GlitchMao User',
    gpgDefaultKeyDomain: process.env.GPG_DEFAULT_KEY_DOMAIN ?? 'glitchmao.local',
    signerServiceUrl: process.env.SIGNER_SERVICE_URL ?? 'http://signer:4000',
    signerSecurityMode: process.env.SIGNER_SECURITY_MODE ?? 'secure',
    signerJwtSecret: process.env.SIGNER_JWT_SECRET ?? '',
    signerJwtTtlSec: process.env.SIGNER_JWT_TTL_SEC ?? '60',
    verificationBaseUrl: process.env.VERIFICATION_BASE_URL ?? 'http://localhost:3000/verify',
    storageProvider: process.env.STORAGE_PROVIDER ?? 'none',
    storageBucket: process.env.STORAGE_BUCKET ?? '',
    storageBaseUrl: process.env.STORAGE_BASE_URL ?? '',
    smtpHost: process.env.SMTP_HOST ?? '',
    smtpPort: process.env.SMTP_PORT ?? '587',
    smtpSecure: process.env.SMTP_SECURE ?? 'false',
    smtpUser: process.env.SMTP_USER ?? '',
    smtpPass: process.env.SMTP_PASS ?? '',
    smtpFrom: process.env.SMTP_FROM ?? '',
    passwordResetBaseUrl: process.env.PASSWORD_RESET_BASE_URL ?? 'http://localhost:3000/reset-password',
  },
})
