import { defineConfig, presetAttributify, presetIcons, presetUno } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons(),
  ],
  theme: {
    fontFamily: {
      sans: 'Inter, ui-sans-serif, system-ui, -apple-system, sans-serif',
      mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
      tech: 'Space Grotesk, ui-sans-serif, system-ui, -apple-system, sans-serif',
    },
    colors: {
      surface: 'var(--color-surface)',
      'surface-dim': 'var(--color-surface-dim)',
      'surface-bright': 'var(--color-surface-bright)',
      'surface-container-lowest': 'rgb(var(--color-surface-container-lowest-rgb) / <alpha-value>)',
      'surface-container-low': 'rgb(var(--color-surface-container-low-rgb) / <alpha-value>)',
      'surface-container': 'rgb(var(--color-surface-container-rgb) / <alpha-value>)',
      'surface-container-high': 'rgb(var(--color-surface-container-high-rgb) / <alpha-value>)',
      'surface-container-highest': 'rgb(var(--color-surface-container-highest-rgb) / <alpha-value>)',
      'on-surface': 'var(--color-on-surface)',
      'on-surface-variant': 'rgb(var(--color-on-surface-variant-rgb) / <alpha-value>)',
      'inverse-surface': 'var(--color-inverse-surface)',
      'inverse-on-surface': 'var(--color-inverse-on-surface)',
      outline: 'var(--color-outline)',
      'outline-variant': 'rgb(var(--color-outline-variant-rgb) / <alpha-value>)',
      'surface-tint': 'var(--color-surface-tint)',
      primary: 'var(--color-primary)',
      'on-primary': 'rgb(var(--color-on-primary-rgb) / <alpha-value>)',
      'primary-container': 'rgb(var(--color-primary-container-rgb) / <alpha-value>)',
      'on-primary-container': 'var(--color-on-primary-container)',
      'inverse-primary': 'var(--color-inverse-primary)',
      secondary: 'var(--color-secondary)',
      'on-secondary': 'var(--color-on-secondary)',
      'secondary-container': 'rgb(var(--color-secondary-container-rgb) / <alpha-value>)',
      'on-secondary-container': 'rgb(var(--color-on-secondary-container-rgb) / <alpha-value>)',
      tertiary: 'var(--color-tertiary)',
      'on-tertiary': 'var(--color-on-tertiary)',
      'tertiary-container': 'var(--color-tertiary-container)',
      'on-tertiary-container': 'var(--color-on-tertiary-container)',
      error: 'var(--color-error)',
      'on-error': 'var(--color-on-error)',
      'error-container': 'rgb(var(--color-error-container-rgb) / <alpha-value>)',
      'on-error-container': 'rgb(var(--color-on-error-container-rgb) / <alpha-value>)',
      background: 'var(--color-background)',
      'on-background': 'var(--color-on-background)',
      'surface-variant': 'var(--color-surface-variant)',
    },
    fontSize: {
      'headline-xl': ['40px', { 'line-height': '1.1', 'letter-spacing': '-0.02em', 'font-weight': '700' }],
      'headline-lg': ['32px', { 'line-height': '1.15', 'letter-spacing': '-0.01em', 'font-weight': '600' }],
      'headline-md': ['24px', { 'line-height': '1.3', 'font-weight': '600' }],
      'body-lg': ['16px', { 'line-height': '1.6', 'font-weight': '400' }],
      'body-md': ['15px', { 'line-height': '1.6', 'font-weight': '400' }],
      'body-base': ['15px', { 'line-height': '1.6', 'font-weight': '400', 'letter-spacing': '0em' }],
      'label-mono': ['13px', { 'line-height': '1.4', 'letter-spacing': '0.05em', 'font-weight': '500' }],
      'data-mono': ['13px', { 'line-height': '1.4', 'letter-spacing': '0.05em', 'font-weight': '500' }],
      'label-caps': ['11px', { 'line-height': '1', 'letter-spacing': '0.15em', 'font-weight': '700' }],
    },
    spacing: {
      xs: '4px',
      sm: '8px',
      md: '16px',
      lg: '24px',
      xl: '48px',
      gutter: '16px',
      margin: '24px',
      'container-padding': '12px',
    },
  },
  shortcuts: {
    'ui-page': 'min-h-screen bg-background text-on-background font-sans',
    'ui-container': 'mx-auto w-full max-w-6xl px-container-padding sm:px-gutter lg:px-margin',
    'ui-input-base': 'w-full border-0 border-b border-outline-variant bg-surface-container-lowest px-2 py-2 text-body-base text-on-surface outline-none transition focus-visible:border-primary-container focus-visible:ring-0 disabled:cursor-not-allowed disabled:opacity-60',
    'ui-button-base': 'inline-flex items-center justify-center gap-2 border px-4 py-2 font-semibold uppercase tracking-[0.12em] transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-container/60 disabled:cursor-not-allowed disabled:opacity-60',
    'ui-label-caps': 'text-label-caps text-on-surface-variant uppercase',
    'ui-meta-mono': 'font-tech text-data-mono text-on-surface-variant',
  },
})
