import { defineConfig, presetAttributify, presetIcons, presetUno } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons(),
  ],
  theme: {
    fontFamily: {
      sans: 'Space Grotesk, ui-sans-serif, system-ui, -apple-system, sans-serif',
      mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    },
    colors: {
      surface: 'var(--color-surface)',
      'surface-dim': 'var(--color-surface-dim)',
      'surface-bright': 'var(--color-surface-bright)',
      'surface-container-lowest': 'var(--color-surface-container-lowest)',
      'surface-container-low': 'var(--color-surface-container-low)',
      'surface-container': 'var(--color-surface-container)',
      'surface-container-high': 'var(--color-surface-container-high)',
      'surface-container-highest': 'var(--color-surface-container-highest)',
      'on-surface': 'var(--color-on-surface)',
      'on-surface-variant': 'var(--color-on-surface-variant)',
      'inverse-surface': 'var(--color-inverse-surface)',
      'inverse-on-surface': 'var(--color-inverse-on-surface)',
      outline: 'var(--color-outline)',
      'outline-variant': 'var(--color-outline-variant)',
      'surface-tint': 'var(--color-surface-tint)',
      primary: 'var(--color-primary)',
      'on-primary': 'var(--color-on-primary)',
      'primary-container': 'var(--color-primary-container)',
      'on-primary-container': 'var(--color-on-primary-container)',
      'inverse-primary': 'var(--color-inverse-primary)',
      secondary: 'var(--color-secondary)',
      'on-secondary': 'var(--color-on-secondary)',
      'secondary-container': 'var(--color-secondary-container)',
      'on-secondary-container': 'var(--color-on-secondary-container)',
      tertiary: 'var(--color-tertiary)',
      'on-tertiary': 'var(--color-on-tertiary)',
      'tertiary-container': 'var(--color-tertiary-container)',
      'on-tertiary-container': 'var(--color-on-tertiary-container)',
      error: 'var(--color-error)',
      'on-error': 'var(--color-on-error)',
      'error-container': 'var(--color-error-container)',
      'on-error-container': 'var(--color-on-error-container)',
      background: 'var(--color-background)',
      'on-background': 'var(--color-on-background)',
      'surface-variant': 'var(--color-surface-variant)',
    },
    fontSize: {
      'headline-xl': ['48px', { 'line-height': '1.1', 'letter-spacing': '-0.02em', 'font-weight': '700' }],
      'headline-lg': ['32px', { 'line-height': '1.2', 'letter-spacing': '-0.01em', 'font-weight': '600' }],
      'headline-md': ['24px', { 'line-height': '1.3', 'font-weight': '600' }],
      'body-lg': ['18px', { 'line-height': '1.6', 'font-weight': '400' }],
      'body-md': ['16px', { 'line-height': '1.5', 'font-weight': '400' }],
      'label-mono': ['14px', { 'line-height': '1.4', 'letter-spacing': '0.05em', 'font-weight': '500' }],
      'label-caps': ['12px', { 'line-height': '1', 'letter-spacing': '0.1em', 'font-weight': '700' }],
    },
    spacing: {
      xs: '4px',
      sm: '12px',
      md: '24px',
      lg: '48px',
      xl: '80px',
      gutter: '24px',
      margin: '32px',
    },
  },
  shortcuts: {
    'ui-page': 'min-h-screen bg-background text-on-background font-sans',
    'ui-container': 'mx-auto w-full max-w-6xl px-4 sm:px-6 lg:px-margin',
    'ui-card': 'border border-outline-variant bg-surface-container text-on-surface',
    'ui-card-header': 'border-b border-outline-variant px-md py-sm',
    'ui-card-content': 'px-md py-md',
    'ui-input-base': 'w-full border border-outline-variant bg-surface-container-low px-3 py-2 text-body-md text-on-surface outline-none transition focus-visible:border-primary-container focus-visible:ring-2 focus-visible:ring-primary-container/50 disabled:cursor-not-allowed disabled:opacity-60',
    'ui-button-base': 'inline-flex items-center justify-center gap-2 border-2 border-transparent px-4 py-2 font-semibold uppercase tracking-[0.08em] transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-container/60 disabled:cursor-not-allowed disabled:opacity-60',
    'ui-label-caps': 'text-label-caps text-on-surface-variant uppercase',
    'ui-meta-mono': 'font-mono text-label-mono text-on-surface-variant',
  },
})
